name: Build and Push Docker Image

on:
  push:
    branches: [main]
    paths:
      - '**/*.py'
      - Dockerfile
      - .github/workflows/docker-publish.yml

env:
  IMAGE_NAME: boomchainlab/chonk9k-whale-tracker

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Slack Notification (Optional)
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Docker Push for ${{ env.IMAGE_NAME }}
          SLACK_MESSAGE: Build ${{ github.sha }} complete on `${{ github.ref_name }}`
